# Generated by Django 4.2.7 on 2024-12-29 00:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prcr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="price",
        ),
        migrations.RemoveField(
            model_name="price",
            name="tags",
        ),
        migrations.AddField(
            model_name="price",
            name="advertised_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                help_text="The initial price you saw for the product",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="comments",
            field=models.CharField(
                blank=True,
                help_text="Describe any misleading pricing claims, if any.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="financing",
            field=models.BooleanField(
                default=False,
                help_text="Must buy financing to get product at advertised price.",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="hidden_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fees added to the advertised price before checkout",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="higher_price_at_checkout",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The price charged at checkout, if it was higher. Leave 0.0 otherwise. Don't apply hidden fees.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="overcharge",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The overcharge price on your card, if higher than at checkout. Leave 0.0 otherwise. Don't apply hidden fees.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="phony_sale",
            field=models.BooleanField(
                default=False,
                help_text="The store lied about how much you saved on the product.",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="tied_sale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tied sale. Add the price of other products you had to buy in order to get the product at advertised price.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
