# Generated by Django 4.2.7 on 2024-12-29 01:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prcr", "0002_remove_price_price_remove_price_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="shipping",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Addes cost for shipping.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="comments",
            field=models.CharField(
                blank=True,
                help_text="Describe any misleading pricing claims.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="hidden_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fees added to the advertised price before checkout, except shipping.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
