# Generated by Django 4.2.7 on 2024-12-29 02:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prcr", "0003_price_shipping_alter_price_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="tied_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tied sale. Add the price of other products you had to buy in order to get the product at advertised price.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tied sale. Add the price of other products you had to buy in order to get the product at advertised price.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="shipping",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Added cost for shipping.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
