# Generated by Django 4.2.7 on 2024-12-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prcr", "0004_price_tied_cost_price_total_alter_price_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="subscription_fees",
            field=models.BooleanField(
                default=False,
                help_text="Price and fees are conditional on subscription or subscription fees may apply.",
            ),
        ),
    ]
