# Generated by Django 4.2.7 on 2024-12-29 18:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prcr", "0005_price_subscription_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="subscription_fees",
            field=models.BooleanField(
                default=False,
                help_text="Price is conditional on subscription or subscription fees may apply.",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="tied_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Cost of buying all bundled products.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="tied_sale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Add the price of other products you had to buy in order to get the product at advertised price.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total cost of final product price and all fees.",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
