# Generated by Django 4.2.7 on 2025-01-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prcr", "0007_comment_likes_userlikes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlikes",
            options={"verbose_name_plural": "User likes"},
        ),
    ]
