# Generated by Django 4.2.7 on 2024-12-22 16:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prcr", "0007_alter_brand_brand_alter_brand_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="company",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Brand name must be longer than two letters."
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("brand", "company")},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Comment must be longer than three characters"
                            )
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="prcr.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="comments",
            field=models.ManyToManyField(
                related_name="product_comments",
                through="prcr.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
